kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ template "helm-guestbook.fullname" . }}
spec:
  to:
    kind: Service
    name: {{ template "helm-guestbook.fullname" . }}
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None
